name: Build Tools Setup
description: This install build tools

inputs:
  python-version:
    required: true
    description: doh


runs:
  using: "composite"
  steps:

    - name: Set up Python ${{ input.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ input.python-version }}

    - name: Install Requirements
      run: pip install -r requirements/dev.txt
