name: Build Tools Setup
description: This install build tools

inputs:
  python-version:
    required: true
    description: doh


runs:
  using: "composite"
  steps:


    - name: Install Requirements
      run: pip install -r requirements/dev.txt
