
name: The Job

on:
  push:
    branches:
      - main

jobs:
  build_setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Build Tool
      uses: actions/build_tools_setup@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: pytest
